language: c

env:
  global:
    - LUAROCKS=2.4.2
    - ROCKSPEC=rockspecs/lpath-scm-0.rockspec
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3
    - LUA=luajit
    # - LUA=luajit2.0
    # - LUA=luajit2.1

branches:
  only:
    - master

before_install:
  - travis_retry bash .travis/setup_lua.sh
  # - sudo pip install cpp-coveralls
  # - sudo luarocks install Lua-cURL         --server=https://rocks.moonscript.org/dev
  # - sudo luarocks install luacov-coveralls --server=https://rocks.moonscript.org/dev
  # - sudo luarocks install lunitx

install:
  # - sudo luarocks make $ROCKSPEC CFLAGS="-O2 -fPIC -ftest-coverage -fprofile-arcs" LIBFLAG="-shared --coverage"
  - sudo luarocks make $ROCKSPEC CFLAGS="-O2 -fPIC" LIBFLAG="-shared"

script: 
  - lua -e "print(require'path.info'.version)"
  - lua test.lua
  # - lunit.sh test.lua

#after_success:
#  - coveralls -b .. -r .. --dump c.report.json
#  - luacov-coveralls -j c.report.json -v

notifications:
  email:
    on_success: change
    on_failure: always

# vim: ft=yaml nu et sw=2 fdc=2 fdm=syntax
